In [1]:
import numpy as np
import pandas as pd
from IPython.display import Image, display, HTML

In [2]:
data=pd.read_csv('prod_.csv')
data.head()

product  year  expiri duretion in years  month  \
0  colgate  2019                       2.0      1   
1  colgate  2019                       2.0      2   
2  colgate  2019                       2.0      3   
3  colgate  2019                       2.0      4   
4  colgate  2019                       2.0      5   

   no. of new products bought    no of products left for selling  \
0                            60                               60   
1                            32                               46   
2                            40                               62   
3                            36                               51   
4                            56                               67   

   no. of products sold  prodects left  no of products to be bought  \
0                    46              0                         46.0   
1                    38             14                         24.0   
2                    47             22                         25.0   
3                    40             15                         25.0   
4                    58             11                         47.0   

     demand %  
0   76.666667  
1  118.750000  
2  117.500000  
3  111.111111  
4  103.571429

In [3]:
unique_ele=data['product'].unique()
unique_ele_dict={}
for i in range(1,len(unique_ele)+1):
    unique_ele_dict[unique_ele[i-1]]=i

data['encoded_product']=data['product'].map(unique_ele_dict)

In [4]:
x = data.iloc[:,[10,1,3]].values
y = data.iloc[:, [6]].values

In [5]:
X_train , X_test = x[:int(len(x)*0.912)], x[int(len(x)*0.912):]
y_train , y_test = y[:int(len(y)*0.912)], y[int(len(y)*0.912):]

In [6]:
from customNNs.ANNmodel import ANNmodel
model=ANNmodel()
model.add(3,5)
model.add(5,4)
model.add(4,5)
model.add(5,3)
model.add(3,1)

([array([[-0.34079922, -0.21047204, -0.99497449,  1.96891448, -0.5081397 ],
         [-0.31424152,  0.1911341 ,  0.56389082, -0.07823576,  1.1622859 ],
         [ 1.73607568,  0.75370906,  1.76489033, -1.67147678,  0.8384542 ]]),
  array([[ 1.25501756,  1.5223752 ,  0.52921221,  0.591489  ],
         [-2.57374657,  1.72590439,  0.11340509, -2.00196375],
         [ 0.81958707, -0.53441026, -0.25682234, -0.60168224],
         [ 1.45449966, -1.42054309,  0.08575983, -1.61930855],
         [ 0.93174537, -0.63240673, -0.75251456, -0.28721873]]),
  array([[-1.14043857,  0.14250989, -1.81257715,  0.39949025,  0.8895264 ],
         [-0.16832875,  0.77585254, -0.70488248,  0.8399151 ,  1.4318189 ],
         [ 1.34347579,  0.18883698,  2.13272191, -1.08896785, -1.95969787],
         [ 0.43644605,  1.07380243, -1.26955767, -0.0291219 , -0.04970331]]),
  array([[ 5.10513883e-01, -8.48531918e-01,  8.31896874e-01],
         [-1.98539114e+00,  1.25359761e+00, -4.59078192e-03],
         [-1.08700715e+

In [7]:
model.train(X_train=X_train,y_train=y_train,e=10)

24049.549019607843
11760.562444351226
11335.302362586544
11320.904757258319
11320.417311932326
11320.400808983371
11320.400250259527
11320.400231343378
11320.400230702951
11320.400230681267


([array([[-3.40799216e-01,  5.71413494e+02, -1.83023623e+02,
           1.96891448e+00, -2.07446924e+02],
         [-3.14241520e-01,  3.33752129e+05, -1.06279819e+05,
          -7.82357580e-02, -1.20823408e+05],
         [ 1.73607568e+00,  1.08107491e+03, -3.42253939e+02,
          -1.67147678e+00, -3.90258436e+02]]),
  array([[ 1.25501756e+00,  1.52237520e+00,  5.29212213e-01,
           5.91489003e-01],
         [-2.51497034e+04,  1.72590439e+00,  1.13405087e-01,
          -2.00196375e+00],
         [-7.35538653e+04, -5.34410262e-01, -2.56822338e-01,
          -6.01682238e-01],
         [ 1.45449966e+00, -1.42054309e+00,  8.57598297e-02,
          -1.61930855e+00],
         [-1.50959029e+05, -6.32406734e-01, -7.52514558e-01,
          -2.87218732e-01]]),
  array([[-1.14043857e+00, -2.28565205e+05, -1.81257715e+00,
          -5.82683246e+04, -9.04419448e+04],
         [-1.68328754e-01,  7.75852544e-01, -7.04882481e-01,
           8.39915096e-01,  1.43181890e+00],
         [ 1.34347579